---
- name: configure tomcat9
  hosts: all
  tasks:
    - name: install tomcat9 and tomcat9-admin
      apt:
        name: "{{item.a}}"
        state: "{{item.b}}"
        update_cache: "{{item.c}}"
      with_items:
        - {a: tomcat9,b: present,c: yes}
        - {a: tomcat9-admin,b: present,c: no}   
    - name: copy tomcat-user.xml file
      copy:
        src: tomcat-users.xml
        dest: /etc/tomcat9
    - name: change the port from 8080 to 9090
      replace:
        regexp: 9090
        replace: 8080
        path: /etc/tomcat9/server.xml
    - name: restart tomcat9
      service:
        name: tomcat9
        state: restarted
    - name: pause for 1min
      pause:
        minutes: 2
    - name: check tomcat9 response on server1
      uri:
        url: "{{item}}"
        status_code: 200
      with_items:
        - http://172.31.34.45:8080
        - http://172.31.32.33:8080
...
    

